### ISSUE TITLE
Would love to see this on maven central

### ISSUE THREAD

**Issue by emmby** [mikaelhg/urlbuilder#23]

**Comment by mikaelhg** [comment]
Sonatype OSSRH project creation request sent.

**Comment by yegor256** [comment]
+1 maybe this link will help you to release to Maven Central faster: http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by mikaelhg** [comment]
Thanks @yegor256, I'll take a look!

**Comment by rattigan** [comment]
+1

**Comment by pvg** [comment]
+1

**Comment by mikaelhg** [comment]
Finally, FINALLY, I'm getting my ass in gear to do something about this.

First BinTray, tomorrow the world!

**Comment by mikaelhg** [comment]
Now on JCenter, next to Maven Central...

https://jcenter.bintray.com/io/mikael/urlbuilder/2.0.5/

**Comment by mikaelhg** [comment]
![Sloth](http://pmdvod.nationalgeographic.com/NG_Video/742/275/140715-baby-sloth-orphanage-rescue-vin_640x360_304699971673.jpg)

**Comment by mikaelhg** [comment]
https://repo1.maven.org/maven2/io/mikael/urlbuilder/2.0.7/
