### ISSUE TITLE
Mixing escaped and yet-not-escaped chars in URL strings throws an exception while create an URI object

### ISSUE THREAD

**Issue by jdevelop** [mikaelhg/urlbuilder#36]
consider Google Translate links:

`http://translate.google.com/translate?hl=auto&langpair=auto|zh-TW&u=http%3A%2F%2Fus6.campaign-archive1.com%2F%3Fu%3Dcbc96c3d7a%26id%3D17fdad33a4%26e%3D`
and 
`http://translate.google.com/translate?hl=auto&langpair=auto%7Czh-TW&u=http%3A%2F%2Fus6.campaign-archive1.com%2F%3Fu%3Dcbc96c3d7a%26id%3D17fdad33a4%26e%3D`

the first one results in 

`Illegal character in query at index 59: http://translate.google.com/translate?hl=auto&langpair=auto|zh-TW&u=http%3A%2F%2Fus6.campaign-archive1.com%2F%3Fu%3Dcbc96c3d7a%26id%3D17fdad33a4%26e%3D`

the second one works just fine

the problem here is the _pipe_ character `|` which is not escaped

perhaps the case when an URL contains both escaped and unescaped characters should be processed in certain way

**Comment by mikaelhg** [comment]
Could you create a pull request with a unit test for this issue?

**Comment by mikaelhg** [comment]
Added these unit tests, which pass. Reopen if I misread something.
