### ISSUE TITLE
Path without leading slash generates incorrect url

### ISSUE THREAD

**Issue by fedotxxl** [mikaelhg/urlbuilder#37]
I'm trying to generate url with `a/b` path. Instead of `http://ya.ru/a/b` I get `http://ya.rua/b`. I think builder should automatically add leading slash

**Comment by mikaelhg** [comment]
Good point, I think the first slash is mandated by the spec. I'll have to look up the particular wording.

**Comment by mikaelhg** [comment]
Thanks for noticing the bug and filing the issue. It's fixed in master.

For future reference:
RFC 3986 section 3.3: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.

**Comment by fedotxxl** [comment]
thanks for fast response!
