### ISSUE TITLE
Plus sign in path portion of URL gets encoded - while still being allowed

### ISSUE THREAD

**Issue by ChristerF** [mikaelhg/urlbuilder#38]
I just want to start off by saying thanks for publishing this project - there is definitely a need for a non-framework attached url builder module. 

According to [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) the plus (+) character is allowed as a character in the path portion of the URL, but according to the code it is being explicitly encoded.

This seems to be a deliberate omission, is there a particular reason for that?

This is a difference to how Jersey's URIBuilder is handling the same thing and making it hard to replace it with this less burdened implementation.

**Comment by mikaelhg** [comment]
Thanks for helping to catch bugs.

 Would you mind submitting a pull request with the relevant test cases, please?

**Comment by ChristerF** [comment]
Mikael, thanks - here is a PR https://github.com/mikaelhg/urlbuilder/pull/39 - would appreciate a release with this fix!

**Comment by mikaelhg** [comment]
Merged, but upload to Sonatype (Maven Central) is failing for some reason...

**Comment by ChristerF** [comment]
Thanks @mikaelhg for the project and for doing this release!
