### ISSUE TITLE
Auto add starting slash with withPath

### ISSUE THREAD

**Issue by paulovictorv** [mikaelhg/urlbuilder#40]
I don't know if it makes any sense, or if it is the intended way the method should work, but I expected the builder to add a starting slash if my path string didn't have one. 

To illustrate, I've created the following piece of code:

``UrlBuilder.fromString("http://withoutslash").withPath("lol")``
which outputs ``http://withoutslashlol`` . My intuition told me to expect ``http://withoutslash/lol``.

What do you think? I can totally work on a PR for this if you decide if it's ok.

**Comment by mikaelhg** [comment]
I thought I'd fixed this already... let's see.

**Comment by mikaelhg** [comment]
If you add this test to the end of the SimpleUrlTest class, does it not pass for you?

```java
    @Test
    public void testWithPathStartingWithNonSlash() {
        UrlBuilder b = UrlBuilder.fromString("http://withoutslash").withPath("lol");
        assertEquals(b.toString(), "http://withoutslash/lol");
    }
```

**Comment by mikaelhg** [comment]
Yeah, this should have been fixed with #37 and the fix released with 2.0.8, which is the latest release on Maven Central.

**Comment by paulovictorv** [comment]
Oh, my bad then. I copied & pasted the dependency listed in the README, it was 2.0.7.

Upgrading to 2.0.8 fixed the issue, thanks for the heads up.

You can close if you want

**Comment by mikaelhg** [comment]
All's well that ends well.
