### ISSUE TITLE
Make Encoder.encodeQueryElement public

### ISSUE THREAD

**Issue by Entea** [mikaelhg/urlbuilder#41]
Sometimes you need to use `io.mikael.urlbuilder.util.Encoder.encodeQueryElement` and I extend the `Encoder` to do that :) Would be great to make it public.

**Comment by mikaelhg** [comment]
Sometimes you need to use it where? A subclass of Encoder, or some other code which directly uses an Encoder instance?

**Comment by Entea** [comment]
I figured out that `Encoder` class can be useful by itself, outside of the `UrlBuilder` class.

In order to use the above mentioned method in my codebase, I need to create a new subclass where I override the method as `public`.

I thought it would be an improvement to make it public here, to avoid the hassle of creating subclasses of `Encoder` in my codebase.

**Comment by mikaelhg** [comment]
OK, sounds sensible.

**Comment by mikaelhg** [comment]
Just released 2.0.9 to Maven Central, should include this.

**Comment by Entea** [comment]
Thanks @mikaelhg !
