### ISSUE TITLE
Faulty fragment matching

### ISSUE THREAD

**Issue by Loki-Afro** [mikaelhg/urlbuilder#43]
When creating an `UrlBuilder` from an existing URL the fragment-parrt is not interpreted right

```
    @Test
    public void test() {
        String existingUrl = "http://localhost:5555/#/aresource?bparameter=cvalue";

        String url = UrlBuilder.fromString(existingUrl)
                .addParameter("d", "parameter")
                .toString();

        assertThat(url, is("http://localhost:5555/#/aresource?bparameter=cvalue&d=parameter"));
    }
```

```
Expected :http://localhost:5555/#/aresource?bparameter=cvalue&d=parameter
Actual   :http://localhost:5555/?d=parameter#/aresource?bparameter=cvalue
```

**Comment by mikaelhg** [comment]
Thanks, I'll take a look.

**Comment by mikaelhg** [comment]
That'll teach me to not read tickets late at night, I thought your ticket was about query parameters inside the fragment leaking to the URL query parameters.

**Comment by mikaelhg** [comment]
@Loki-Afro Please take a look at https://tools.ietf.org/html/rfc3986 and also add the part of the spec which the current implementation infringes, to the issue text. Especially section 3.5.

**Comment by Loki-Afro** [comment]
@mikaelhg I'm not sure sure how to understand that part of rfc3986. But since Jetty and other libs do not have any problem distinguishing between the fragment part and an url parameter my url seems valid.

Here is the reason why it is there at all; https://stackoverflow.com/a/14320468/1248724

**Comment by mikaelhg** [comment]
```
http://localhost:5555/#/aresource?bparameter=cvalue ->
schema: http
host: localhost
port: 5555
path: /
query: <null>
fragment: #/aresource?bparameter=cvalue
```

If you construct a builder with it and call `builder.addParameter("d", "parameter")`, it becomes:

```
schema: http
host: localhost
port: 5555
path: /
query: d=parameter
fragment: #/aresource?bparameter=cvalue
```

which is then concatenated as 

```
<schema>://<host>:<port>/<path>?<query>#<fragment>
http://localhost:5555/?d=parameter#/aresource?bparameter=cvalue
```

**Comment by Loki-Afro** [comment]
```
fragment: #/aresource?bparameter=cvalue
```
is not correct. There is no fragment in the URI, `/#/aresource` is the path

**Comment by mikaelhg** [comment]
No, `/` is the path. Anything coming after the path and after a `#` character is the fragment. The fragment is just arbitrary data, which some client side web frameworks use to encode data in a non-standardized manner.

**Comment by mikaelhg** [comment]
Please reopen the issue if you find a section of the RFC that we're violating.
