### ISSUE TITLE
Ability to append to the path

### ISSUE THREAD

**Issue by cowwoc** [mikaelhg/urlbuilder#48]
I am looking for something similar to the JAX-RS method `UriBuilder.path()` which appends to the existing path.

**Comment by mikaelhg** [comment]
`.withPath(x.path + "/foobar")`?

**Comment by mikaelhg** [comment]
https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriBuilder.html#path-java.lang.String-

All right. What's your "business-level" use case for this, a one-sentence explanation is fine?

**Comment by cowwoc** [comment]
Honestly, I don't really need this feature any more.

1. Because I decided to code to Jetty client directly.
2. I realized that this feature was a lazy way of avoiding a compile-time decision as to whether a slash is necessary.

You can close this issue if you wish. Thank you.

**Comment by tekhedd** [comment]
I realize the name of the class is "URL" builder, but it really builds URIs, does it not? 

I would use an "appendPath()" method if it was there, just as convenience, but whether it would collapse slashes is something I would expect to be documented, as that's a grey area. While it seems like a one-liner it's actually a fair bit of code that also needs to be optional.

With a URI (not a URL!), multiple consective slashes have a defined meaning, so collapsing the slashes should not happen by default. This does not apply to URLs...mostly. When making a request, http://foo/bar is the same as http://foo//bar (but is entirely different from "http://foo/bar/"). I assume this is why some UriBuilder implementations automatically collapse slashes and ".." navigation, but this can be annoying if it is not desired behavior.  I have seen (rare) bug reports where people could not disable this default behavior in UriBuilder and had to manually construct paths.

HTTP servers will/should ignore consecutive slashes whether you like it or not, but they have a specific meaning in URIs and should *not* be automatically collapsed. :/ Browsers use URLs for different reasons and are unpredictable. So, need to collapse or remove slashes is for presentation or for non-HTTP usage (when path is also used in cookies etc).

So, I can see how a method that explicitly collapses multiple slashes could be occasionally useful. normalizePath() or something?

Just a thought. I'm good regardless. Love the project, its goals, and it simplicity. I've just been thinking about this anyway, and found the bug report.

**Comment by mikaelhg** [comment]
Thanks @tekhedd, I very much appreciate your thoughtful comment.

**Comment by Loki-Afro** [comment]
@mikaelhg i would like to see a method like `appendPath` which inserts a slash at the beginning if it is not supplied from the existing url or the appended string.

```
    @Test
    public void somethingLikeThat(){
        UrlBuilder urlBuilder = UrlBuilder.fromString("http://localhost:4200/check-in/");
        String s = urlBuilder.withPath(urlBuilder.path + "555Nose").toString();
        
        assertThat(s).isEqualTo("http://localhost:4200/check-in/555Nose");

        assertThat(UrlBuilder.fromString("http://localhost:4200/check-in/").appendToPath("555Nase").toString()).isEqualTo("http://localhost:4200/check-in/555Nose");
    }
```

**Comment by Loki-Afro** [comment]
@mikaelhg thank you ;)
