### ISSUE TITLE
question: is there any Java or commonly used open source alternative?

### ISSUE THREAD

**Issue by nmarasoiu** [mikaelhg/urlbuilder#49]
Hi, and congrats for the great piece of software. In our project we try to minimize dependencies but we already have Commons Http, Guava and other commonly used Java library and we use Java 15 OpenJdk. 
Would you know if there is any chance that the wonderful functionality you implemented in this library could be reconstructed in a decent way using the OpenJdk and some of the Commons / Guava libraries?
I think the answer is not really, but i will certainly be asked about that before deciding to import a new dependency.
Thank you very much

**Comment by mikaelhg** [comment]
Since 2011, at least Spring Framework and Apache HttpClient 4 have pretty good URI builders.

**Comment by nmarasoiu** [comment]
Thank a lot for your answer
