### ISSUE TITLE
Does this library has max string limit??

### ISSUE THREAD

**Issue by harmeet-sidhu** [mikaelhg/urlbuilder#50]
I am using this library for my maven project. The issue is that sometimes URI generated by this library does not include last 1-3 characters from string that I passed to build URI.

**Comment by mikaelhg** [comment]
Do you have a unit test or other demonstration of this happening?

**Comment by mikaelhg** [comment]
The quickest way to get this fixed would be to submit a PR with a unit test demonstrating this issue.

**Comment by mikaelhg** [comment]
Can't reproduce. No response. If you can reproduce this issue, please reopen it.
